# Generated by Django 5.1.4 on 2025-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorRTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtc', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='RTC')),
                ('current_1', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Corriente 1')),
                ('current_2', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Corriente 2')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatorRTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtp', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='RTP')),
                ('voltage_1', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Voltaje 1')),
                ('voltage_2', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Voltaje 2')),
            ],
        ),
    ]
