# Generated by Django 5.1.4 on 2025-01-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_1',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Voltaje 1'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_2',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Voltaje 2'),
        ),
    ]
