# Generated by Django 5.1.4 on 2025-01-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_calculatorrtc_error_rtc_calculatorrtc_rtc_cal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorrtc',
            name='rtc',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='RTC'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='rtp',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='RTP'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_1',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Voltaje 1'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_2',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Voltaje 2'),
        ),
    ]
