# Generated by Django 5.1.4 on 2025-01-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_alter_calculatorrtc_rtc_alter_calculatorrtp_rtp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorrtc',
            name='current_1',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Corriente 1'),
        ),
        migrations.AlterField(
            model_name='calculatorrtc',
            name='current_2',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Corriente 2'),
        ),
        migrations.AlterField(
            model_name='calculatorrtc',
            name='error_rtc',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='%Error RTC'),
        ),
        migrations.AlterField(
            model_name='calculatorrtc',
            name='rtc',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='RTC'),
        ),
        migrations.AlterField(
            model_name='calculatorrtc',
            name='rtc_cal',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='RTC Calc'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='error_rtc',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='%Error RTP'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='rtp',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='RTP'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='rtp_cal',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='RTP Calc'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_1',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Voltaje 1'),
        ),
        migrations.AlterField(
            model_name='calculatorrtp',
            name='voltage_2',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Voltaje 2'),
        ),
    ]
